version: '3.7'

services:
  app:
    container_name: simple-react-full-stack
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './data:/data'
      - '/app/node_modules'
    links:
      - mongo
    ports:
      - '0.0.0.0:3000:3000'
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
